# Generated by Django 3.1.1 on 2021-02-26 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorites_recipe',
        ),
    ]
