# Generated by Django 3.1.1 on 2021-02-28 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_auto_20210226_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Тэги',
            },
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='breakfast',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='dinner',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='lunch',
        ),
        migrations.CreateModel(
            name='RecipeTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipetag', to='recipe.recipe', verbose_name='Название рецепта')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipetag', to='recipe.tag', verbose_name='Название тэга')),
            ],
            options={
                'verbose_name': 'Тэги рецепта',
                'verbose_name_plural': 'Тэги рецепта',
                'unique_together': {('recipe', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', through='recipe.RecipeTags', to='recipe.Tag', verbose_name='Тэги'),
        ),
    ]
