# Generated by Django 3.1.1 on 2021-03-12 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0011_auto_20210312_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(related_name='tags', through='recipe.RecipeTags', to='recipe.Tag', verbose_name='Тэги'),
        ),
    ]
