# Generated by Django 3.1.1 on 2021-02-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorites_recipe',
            options={'verbose_name': 'избранное', 'verbose_name_plural': 'избранные'},
        ),
        migrations.AddConstraint(
            model_name='favorites_recipe',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_favorites'),
        ),
    ]
