# Generated by Django 3.1.1 on 2021-02-26 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_auto_20210226_0947'),
        ('api', '0003_auto_20210226_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_recipe', to='recipe.recipe'),
        ),
    ]
