# Generated by Django 3.1.1 on 2021-03-06 12:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0008_auto_20210302_2230'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0007_cart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favorites_recipe',
            new_name='FavoritesRecipe',
        ),
    ]
